"use client";

import React, { useState } from "react";
import { cn } from "@/lib/utils";

type Source = "user-entered" | "ai-extracted" | "ai-generated";

interface SourceBorderProps {
  source: Source;
  className?: string;
  children: React.ReactNode;
  showLabel?: boolean;
}

const SOURCE_CONFIG: Record<
  Source,
  { borderClass: string; label: string; labelColor: string; description: string }
> = {
  "user-entered": {
    borderClass: "border-l-2 border-l-transparent",
    label: "User-entered",
    labelColor: "text-ink/50",
    description: "Information entered directly by the clinician or patient",
  },
  "ai-extracted": {
    borderClass: "border-l-2 border-l-accent",
    label: "AI-extracted",
    labelColor: "text-accent",
    description: "Extracted from uploaded documents by AI — verify before clinical use",
  },
  "ai-generated": {
    borderClass: "border-l-2 border-l-ai-generated",
    label: "AI-generated",
    labelColor: "text-ai-generated",
    description:
      "Generated by AI based on structured record data — not a clinical assessment",
  },
};

export function SourceBorder({
  source,
  className,
  children,
  showLabel = false,
}: SourceBorderProps) {
  const [hovered, setHovered] = useState(false);
  const config = SOURCE_CONFIG[source];

  return (
    <div
      className={cn(
        "relative pl-3 py-0.5",
        config.borderClass,
        "transition-all duration-150",
        className
      )}
      onMouseEnter={() => setHovered(true)}
      onMouseLeave={() => setHovered(false)}
      onFocus={() => setHovered(true)}
      onBlur={() => setHovered(false)}
    >
      {children}

      {/* Provenance label — shown on hover/focus or if showLabel is true */}
      {(hovered || showLabel) && (
        <span
          className={cn(
            "absolute -top-5 left-3 text-2xs font-sans font-medium whitespace-nowrap",
            "bg-surface border border-line rounded px-1.5 py-0.5 shadow-xs z-10",
            config.labelColor
          )}
          role="tooltip"
        >
          {config.label}: {config.description}
        </span>
      )}

      {/* Always-visible compact label option */}
      {!hovered && !showLabel && source !== "user-entered" && (
        <span
          className={cn(
            "sr-only"
          )}
        >
          Source: {config.label}
        </span>
      )}
    </div>
  );
}

/** Inline provenance badge for use in table rows */
export function ProvenanceBadge({ source }: { source: Source }) {
  const config = SOURCE_CONFIG[source];
  return (
    <span
      className={cn(
        "inline-flex items-center text-2xs font-medium rounded px-1 py-0.5",
        source === "ai-extracted" && "text-accent bg-accent/8",
        source === "ai-generated" && "text-ai-generated bg-ai-generated/8",
        source === "user-entered" && "text-ink/50 bg-ink/5"
      )}
      title={config.description}
    >
      {config.label}
    </span>
  );
}
